### ISSUE TITLE
Produces mets:file/ID that are not a valid xs:ID with certain configurations

### ISSUE THREAD

**Issue by kba** [bertsky/workflow-configuration#18]
In particular, `+` and `/` are not allowed in `mets:file/@ID`.

**Comment by bertsky** [comment]
What part of this repo do you mean in particular? The workflows makefilization itself, or `ocrd-import`?

**Comment by kba** [comment]
The makefilization, which can lead to fileGrps that contain e.g. `Fraktur+Latin` or file IDs concatentating fileGrp and ID with `/`. For example, https://github.com/OCR-D/assets/tree/master/data/kant_aufklaerung_1784-complex/data

**Comment by bertsky** [comment]
> The makefilization, which can lead to fileGrps that contain e.g. `Fraktur+Latin`

ah, I see, you mean the **configuration examples**. Yes, now that I know `+` is forbidden, I should rename these target fileGrps. (But I don't think the makefilization itself should do anything to check output fileGrps, just as `ocrd process` or the single-CLI decorator don't.)

> or file IDs concatentating fileGrp and ID with `/`.

oh, how is that? You surely mean there are certain processors which are behaving that way, not the makefilization, right?

**Comment by kba** [comment]
> oh, how is that? You surely mean there are certain processors which are behaving that way, not the makefilization, right?

tbh, I was just noting the issue with the "complex" sample while fixing it in OCR-D/assets. I'll check what exactly went awry with that particular workflow next week.

**Comment by bertsky** [comment]
> ah, I see, you mean the **configuration examples**. Yes, now that I know `+` is forbidden, I should rename these target fileGrps.

see https://github.com/bertsky/workflow-configuration/commit/7edcb9054778c418a484119854d3343066ef7f85
