### ISSUE TITLE
workflow-configuration not running

### ISSUE THREAD

**Issue by EEngl52** [bertsky/workflow-configuration#4]
I adapted gt-binarize-page-olena-sauvola-clip-resegment-dewarp-ocr-ocropy-tesseract.mk by renaming the input file group and exchanging the first processor olena-binarize with cis-ocropy-binarize (see attachment).

When I try to run `make -r test.mk /test/data/helmstedt` or `-f` it would just tell me that there's nothing to do in this workspace. The same holds true when using a relative path to the workspace. `-s` doesn't return any message.

[test.zip](https://github.com/bertsky/workflow-configuration/files/3988382/test.zip)

**Comment by bertsky** [comment]
Looking into it now.

Just 2 things ahead:
- `-r` is wrong here. (You use that option to tell `make` to exclude its database of suffix rules.) You always need `-f` to select the configuration makefile.
- `-s` tells `make` to run _silent_ (i.e. without showing the commands executed). You probably intended the opposite, `-d` (debugging the traversal of rules that leads up to the commands).

**Comment by bertsky** [comment]
Okay, at that point – without your input data – I need your help. Can you please show the result of running `LC_MESSAGES=C make -d -f test.mk helmstedt`?

BTW, this configuration is not going to work anyway:
```make
$(BIN): TOOL = ocrd-cis-ocropy-binarize
$(BIN): PARAMS = "level-of-operation": "line"

CLIP = $(BIN)-CLIP

$(CLIP): $(BIN)
$(CLIP): TOOL = ocrd-cis-ocropy-clip
```

...because you cannot clip segments that already have AlternativeImage on them – this makes them incomparable. (Derived images one level above the `level-of-operation` are fine of course.) So your binarization needs to use `PARAMS = "level-of-operation": "page"`.

**Comment by EEngl52** [comment]
ah, ok, thanks for your explanations

there's the output from your command. I could also zip my workspace and upload it if that helps
[output.txt](https://github.com/bertsky/workflow-configuration/files/3988515/output.txt)

**Comment by bertsky** [comment]
Are you sure you ran with `helmstedt` not with the absolute path?

Sorry, I know this should be irrelevant. Just trying to understand.

Also, yes, if it's possible, please upload your workspace (the mets.xml and empty directories will sufffice though).

**Comment by EEngl52** [comment]
sorry, used the absolute path. there's the output for helmstedt

[erroutput.txt](https://github.com/bertsky/workflow-configuration/files/3988642/erroutput.txt)

and there's my workspace. I had to delete the original images in OCR-D-IMG as they were too big to upload

[helmstedt.zip](https://github.com/bertsky/workflow-configuration/files/3988655/helmstedt.zip)

**Comment by EEngl52** [comment]
just changed level of operation to page and ran it on a new workspace with just OCR-D-IMG as input. This also produced the same error message

**Comment by bertsky** [comment]
I think I know what the issue is. This happens when you don't **install** (as documented by the README). However, I am thinking of a solution without installation anyway...

**Comment by bertsky** [comment]
... the current master should allow that usage now (and also complain when no workspaces can be found). @EEngl52 could you please try it out, so we can close?

**Comment by EEngl52** [comment]
I just updated and tried the new version. It works perfectly fine, also with relative paths. thx @bertsky !!
