### ISSUE TITLE
Download images first

### ISSUE THREAD

**Issue by wrznr** [bertsky/workflow-configuration#5]
When using `workflow-configuration`, it is mandatory that the image files are physically present. I.e. you can not make use of `ocrd`'s ability to download images ad-hoc given the corresponding entries in a METS file group. Downloading is best done via
```
$ ocrd workspace find -G USE --download
```
Where `USE` corresponds to the attribute of the file group you want to use as input. Maybe this should be added to the documentation?

**Comment by bertsky** [comment]
Absolutely! This should be the first step for every workflow not starting with `ocrd-import`. I'll see to it this will also be prominent for custom/new configurations.

**Comment by bertsky** [comment]
On the other hand, there is already `gt.mk`, which does exactly this for all known GT file groups (including `OCR-D-IMG`). So you could always do `make -f gt.mk` before anything else. But that's a different strategy, of course...

**Comment by bertsky** [comment]
Anyway, fixed via 1dfe678.
