### ISSUE TITLE
Make fails because .DEFAULT_GOAL contains more than one target

### ISSUE THREAD

**Issue by stweil** [bertsky/workflow-configuration#8]
`.DEFAULT_GOAL` has targets in `Makefile` and in `*.mk` files.

Most of them are identical, therefore redundant and could be removed.

For `ocrd-make -f crop-anyocr-binarize-page-olena-sauvola-denoise-ocropy-deskew-page-ocropy-segment-tesseract-ocropy-shrink-dewarp-ocr-ocropy-tesseract.mk`, both targets are different and `ocrd-make` aborts with an error:

    make: *** .DEFAULT_GOAL contains more than one target.  Stop.

**Comment by bertsky** [comment]
> `.DEFAULT_GOAL` has targets in `Makefile` and in `*.mk` files.

That is intentional (see README under implementation): One is the default target inside workspaces (and this could be different for each configuration), the other is on the global level. The inner level runs in a recursive call to make. Overriding this variable is allowed according to make's documentation.

> Most of them are identical, therefore redundant and could be removed.

No they cannot. It's up to the workflow configuration to decide what the resulting overall annotation should be (and what its name should be). The example configurations contained in the repo are just that: examples.

> `ocrd-make` aborts with an error:
> 
> ```
> make: *** .DEFAULT_GOAL contains more than one target.  Stop.
> ```

That's interesting. Please be more specific: What version of make do you have? Can you show the result of running with the `-d` switch?

**Comment by stweil** [comment]
I can reproduce it with GNU Make 3.81 (macOS) and GNU Make 4.2.1 (Debian GNU Linux).

**Comment by stweil** [comment]
Example on macOS with `-d` switch:

    % make -f crop-anyocr-binarize-page-olena-sauvola-denoise-ocropy-deskew-page-ocropy-segment-tesseract-ocropy-shrink-dewarp-ocr-ocropy-tesseract.mk -d
    GNU Make 3.81
    Copyright (C) 2006  Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.
    There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
    PARTICULAR PURPOSE.

    This program built for i386-apple-darwin11.3.0
    Reading makefiles...
    Reading makefile `crop-anyocr-binarize-page-olena-sauvola-denoise-ocropy-deskew-page-ocropy-segment-tesseract-ocropy-shrink-dewarp-ocr-ocropy-tesseract.mk'...
    Reading makefile `Makefile' (search path) (no ~ expansion)...
    Updating makefiles....
     Considering target file `Makefile'.
      Finished prerequisites of target file `Makefile'.
     No need to remake target `Makefile'.
     Considering target file `crop-anyocr-binarize-page-olena-sauvola-denoise-ocropy-deskew-page-ocropy-segment-tesseract-ocropy-shrink-dewarp-ocr-ocropy-tesseract.mk'.
      Looking for an implicit rule for `crop-anyocr-binarize-page-olena-sauvola-denoise-ocropy-deskew-page-ocropy-segment-tesseract-ocropy-shrink-dewarp-ocr-ocropy-tesseract.mk'.
      Trying pattern rule with stem `crop-anyocr-binarize-page-olena-sauvola-denoise-ocropy-deskew-page-ocropy-segment-tesseract-ocropy-shrink-dewarp-ocr-ocropy-tesseract'.
      Found an implicit rule for `crop-anyocr-binarize-page-olena-sauvola-denoise-ocropy-deskew-page-ocropy-segment-tesseract-ocropy-shrink-dewarp-ocr-ocropy-tesseract.mk'.
      Finished prerequisites of target file `crop-anyocr-binarize-page-olena-sauvola-denoise-ocropy-deskew-page-ocropy-segment-tesseract-ocropy-shrink-dewarp-ocr-ocropy-tesseract.mk'.
     No need to remake target `crop-anyocr-binarize-page-olena-sauvola-denoise-ocropy-deskew-page-ocropy-segment-tesseract-ocropy-shrink-dewarp-ocr-ocropy-tesseract.mk'.
    make: *** .DEFAULT_GOAL contains more than one target.  Stop.

**Comment by bertsky** [comment]
@stweil thank you. I was not seeing the wood from the trees. This configuration needed a pseudo-target to collect all the others without actually comparing them. Fixed in 40b5e86
